set test "print"
set ::result_string {hello world
777
hello world
hello world
foo
foobar
foobar
foobar
foo99
99foo
777
888
123456789
hello999
999hello}

foreach runtime [get_runtime_list] {
    if {$runtime != ""} {
	stap_run2 $srcdir/$subdir/$test.stp --runtime=$runtime
	stap_run2 $srcdir/$subdir/$test.stp --runtime=$runtime -DSTP_LEGACY_PRINT
    } else {
	stap_run2 $srcdir/$subdir/$test.stp
	stap_run2 $srcdir/$subdir/$test.stp -DSTP_LEGACY_PRINT
    }
}
