set test "string1"
set ::result_string {The string is <Foobar!>
Foobar!XYZZY
XYZZYFoobar!XYZZYFoobar!}

foreach runtime [get_runtime_list] {
    if {$runtime != ""} {
	stap_run2 $srcdir/$subdir/$test.stp --runtime=$runtime
	stap_run2 $srcdir/$subdir/$test.stp --runtime=$runtime -DSTP_LEGACY_PRINT
    } else {
	stap_run2 $srcdir/$subdir/$test.stp
	stap_run2 $srcdir/$subdir/$test.stp -DSTP_LEGACY_PRINT
    }
}
